/* Generated By:JavaCC: Do not edit this line. MyParserConstants.java */
package pl.frontend;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MyParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int letter = 3;
  /** RegularExpression Id. */
  int positiveDigit = 4;
  /** RegularExpression Id. */
  int digit = 5;
  /** RegularExpression Id. */
  int decimalPart = 6;
  /** RegularExpression Id. */
  int exponentialPart = 7;
  /** RegularExpression Id. */
  int hexDigit = 8;
  /** RegularExpression Id. */
  int TRUE = 9;
  /** RegularExpression Id. */
  int FALSE = 10;
  /** RegularExpression Id. */
  int INT = 11;
  /** RegularExpression Id. */
  int BOOL = 12;
  /** RegularExpression Id. */
  int FLOAT = 13;
  /** RegularExpression Id. */
  int CHAR = 14;
  /** RegularExpression Id. */
  int STRING = 15;
  /** RegularExpression Id. */
  int STRUCT = 16;
  /** RegularExpression Id. */
  int TYPE = 17;
  /** RegularExpression Id. */
  int VAR = 18;
  /** RegularExpression Id. */
  int WHILE = 19;
  /** RegularExpression Id. */
  int DO = 20;
  /** RegularExpression Id. */
  int IF = 21;
  /** RegularExpression Id. */
  int THEN = 22;
  /** RegularExpression Id. */
  int ELSE = 23;
  /** RegularExpression Id. */
  int SWITCH = 24;
  /** RegularExpression Id. */
  int CASE = 25;
  /** RegularExpression Id. */
  int DEFAULTINST = 26;
  /** RegularExpression Id. */
  int PROC = 27;
  /** RegularExpression Id. */
  int CALL = 28;
  /** RegularExpression Id. */
  int WITH = 29;
  /** RegularExpression Id. */
  int NULL = 30;
  /** RegularExpression Id. */
  int NEW = 31;
  /** RegularExpression Id. */
  int DELETE = 32;
  /** RegularExpression Id. */
  int READ = 33;
  /** RegularExpression Id. */
  int WRITE = 34;
  /** RegularExpression Id. */
  int ident = 35;
  /** RegularExpression Id. */
  int intLiteral = 36;
  /** RegularExpression Id. */
  int realLiteral = 37;
  /** RegularExpression Id. */
  int charLiteral = 38;
  /** RegularExpression Id. */
  int stringLiteral = 39;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<token of kind 1>",
    "<token of kind 2>",
    "<letter>",
    "<positiveDigit>",
    "<digit>",
    "<decimalPart>",
    "<exponentialPart>",
    "<hexDigit>",
    "<TRUE>",
    "<FALSE>",
    "<INT>",
    "<BOOL>",
    "<FLOAT>",
    "<CHAR>",
    "<STRING>",
    "<STRUCT>",
    "<TYPE>",
    "<VAR>",
    "<WHILE>",
    "<DO>",
    "<IF>",
    "<THEN>",
    "<ELSE>",
    "<SWITCH>",
    "<CASE>",
    "<DEFAULTINST>",
    "<PROC>",
    "<CALL>",
    "<WITH>",
    "<NULL>",
    "<NEW>",
    "<DELETE>",
    "<READ>",
    "<WRITE>",
    "<ident>",
    "<intLiteral>",
    "<realLiteral>",
    "<charLiteral>",
    "<stringLiteral>",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"&\"",
    "\"*\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\"=\"",
    "\":\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"||\"",
    "\"+\"",
    "\"-\"",
    "\"&&\"",
    "\"/\"",
    "\"%\"",
    "\"!\"",
    "\"_\"",
    "\".\"",
    "\"->\"",
  };

}
